// Generated by Wrangler on Tue Dec 03 2024 14:12:34 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	keyValueStore: KVNamespace;
	PLUGIN_PARENT_DOMAIN: "plugins.framercdn.com";
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_ID: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
