#:schema node_modules/wrangler/config-schema.json
name = "polar-framer"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "polar-framer", id = "cd711711ac8647bca3fabac9967521d1" },
]

[vars]
PLUGIN_PARENT_DOMAIN = "plugins.framercdn.com"
