#:schema node_modules/wrangler/config-schema.json
name = "polar-framer"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "polar-framer", id = "cd711711ac8647bca3fabac9967521d1" },
]

[vars]
PLUGIN_PARENT_DOMAIN = "plugins.framercdn.com"
PLUGIN_ID="a4cab2"
AUTHORIZE_ENDPOINT="https://polar.sh/oauth2/authorize"
TOKEN_ENDPOINT="https://api.polar.sh/v1/oauth2/token"
SCOPE="openid,profile,email,user:read,organizations:read,organizations:write,checkout_links:read,checkout_links:write,products:read,products:write,benefits:read,benefits:write,files:read,files:write"
